
package cinematicketing;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.*;


public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        purchasePanel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        selectFilm = new javax.swing.JLabel();
        filmDD = new javax.swing.JComboBox<>();
        selectTicket = new javax.swing.JLabel();
        ticketDD = new javax.swing.JComboBox<>();
        basketBtn = new javax.swing.JButton();
        selectDate = new javax.swing.JLabel();
        dayDD = new javax.swing.JComboBox<>();
        monthDD = new javax.swing.JComboBox<>();
        yearDD = new javax.swing.JComboBox<>();
        selectTime = new javax.swing.JLabel();
        timeDD = new javax.swing.JComboBox<>();
        summaryBtn = new javax.swing.JButton();
        purchaseTicket = new javax.swing.JLabel();
        summaryPanel = new javax.swing.JPanel();
        summary = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        removeTicket = new javax.swing.JButton();
        paymentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        selectFilm.setText("Select Film:");

        filmDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black Panther", "Avengers: Infinity War", "Jurassic World", "Spider Man: Homecoming", "Captain Marvel" }));
        filmDD.setSelectedIndex(-1);
        filmDD.setFocusable(false);

        selectTicket.setText("Select Ticket:");

        ticketDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "OAP", "Student", "Child" }));
        ticketDD.setSelectedIndex(-1);
        ticketDD.setFocusable(false);

        basketBtn.setText("Add to Basket");
        basketBtn.setFocusable(false);
        basketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketBtnActionPerformed(evt);
            }
        });

        selectDate.setText("Select Date:");

        dayDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayDD.setSelectedIndex(-1);
        dayDD.setFocusable(false);
        dayDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayDDActionPerformed(evt);
            }
        });

        monthDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec" }));
        monthDD.setSelectedIndex(-1);
        monthDD.setFocusable(false);
        monthDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthDDActionPerformed(evt);
            }
        });

        yearDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019" }));
        yearDD.setSelectedIndex(-1);
        yearDD.setFocusable(false);

        selectTime.setText("Select Time:");

        timeDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:15", "14:30", "15:45", "18:15", "20:00", "22:50" }));
        timeDD.setSelectedIndex(-1);
        timeDD.setFocusable(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(selectFilm)
                        .addGap(30, 30, 30)
                        .addComponent(filmDD, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectTicket)
                            .addComponent(selectDate)
                            .addComponent(selectTime))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ticketDD, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(dayDD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(monthDD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yearDD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(timeDD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                                .addComponent(basketBtn)))))
                .addGap(28, 28, 28))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFilm))
                .addGap(23, 23, 23)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectTicket)
                    .addComponent(ticketDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDate)
                    .addComponent(dayDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectTime))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addComponent(basketBtn)
                        .addContainerGap())))
        );

        summaryBtn.setText("Summary");
        summaryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        summaryBtn.setFocusable(false);
        summaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryBtnActionPerformed(evt);
            }
        });

        purchaseTicket.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        purchaseTicket.setText("Purchase Ticket");

        javax.swing.GroupLayout purchasePanelLayout = new javax.swing.GroupLayout(purchasePanel);
        purchasePanel.setLayout(purchasePanelLayout);
        purchasePanelLayout.setHorizontalGroup(
            purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purchasePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(summaryBtn)
                .addGap(14, 14, 14))
            .addGroup(purchasePanelLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(purchaseTicket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        purchasePanelLayout.setVerticalGroup(
            purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(purchaseTicket)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(summaryBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Purchase ticket", purchasePanel);

        summary.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        summary.setText("Summary");
        summary.setLocation(new java.awt.Point(-32461, -32692));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Film", "Ticket Price", "Date", "Time"
            }
        ));
        jTable1.setFocusable(false);
        jScrollPane1.setViewportView(jTable1);

        removeTicket.setText("Remove selected");
        removeTicket.setFocusable(false);
        removeTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout summaryPanelLayout = new javax.swing.GroupLayout(summaryPanel);
        summaryPanel.setLayout(summaryPanelLayout);
        summaryPanelLayout.setHorizontalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(summaryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
                    .addGroup(summaryPanelLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(summary)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(removeTicket)
                .addGap(26, 26, 26))
        );
        summaryPanelLayout.setVerticalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(summary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(removeTicket)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Summary", summaryPanel);

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Payment", paymentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void basketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketBtnActionPerformed
        
        final int standard = 8, oap = 6, student = 6, child = 4;
        discount dis = new discount();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        
        if (filmDD.getSelectedItem() == null || ticketDD.getSelectedItem() == null || dayDD.getSelectedItem() == null || monthDD.getSelectedItem() == null || yearDD.getSelectedItem() == null || timeDD.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Please select all fields.");
        }
        else if (ticketDD.getSelectedItem().equals("Standard")) {
            int Standard = dis.applyDiscount(standard);
            model.addRow(new Object[] {filmDD.getSelectedItem(),"£"+Standard+"  ("+ticketDD.getSelectedItem()+")",dayDD.getSelectedItem()+"/"+monthDD.getSelectedItem()+"/"+yearDD.getSelectedItem(),timeDD.getSelectedItem()});
        }
        else if (ticketDD.getSelectedItem().equals("OAP")) {
            int OAP = dis.applyDiscount(oap);
            model.addRow(new Object[] {filmDD.getSelectedItem(),"£"+OAP+"  ("+ticketDD.getSelectedItem()+")",dayDD.getSelectedItem()+"/"+monthDD.getSelectedItem()+"/"+yearDD.getSelectedItem(),timeDD.getSelectedItem()});
        }
        else if (ticketDD.getSelectedItem().equals("Student")) {
            int Student = dis.applyDiscount(student);
            model.addRow(new Object[] {filmDD.getSelectedItem(),"£"+Student+"  ("+ticketDD.getSelectedItem()+")",dayDD.getSelectedItem()+"/"+monthDD.getSelectedItem()+"/"+yearDD.getSelectedItem(),timeDD.getSelectedItem()});
        }
        else if (ticketDD.getSelectedItem().equals("Child")) {
            int Child = dis.applyDiscount(child);
            model.addRow(new Object[] {filmDD.getSelectedItem(),"£"+Child+"  ("+ticketDD.getSelectedItem()+")",dayDD.getSelectedItem()+"/"+monthDD.getSelectedItem()+"/"+yearDD.getSelectedItem(),timeDD.getSelectedItem()});
        } else {}
    }//GEN-LAST:event_basketBtnActionPerformed

    private void summaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryBtnActionPerformed

        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_summaryBtnActionPerformed

    private void monthDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthDDActionPerformed
        
    }//GEN-LAST:event_monthDDActionPerformed

    private void dayDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayDDActionPerformed
   
//        String day = dayDD.getSelectedItem().toString();
//        int selectedItem = Integer.parseInt(day);
//        
//        if (selectedItem > 28) {
//            monthDD.removeItem("Feb");
//        }
//        else if (selectedItem <= 28) {
//            if (monthDD.getItemAt(1) != "Feb") {
//                monthDD.insertItemAt("Feb", 1);
//            }
//        }
    }//GEN-LAST:event_dayDDActionPerformed

    private void removeTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTicketActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_removeTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton basketBtn;
    private javax.swing.JComboBox<String> dayDD;
    private javax.swing.JComboBox<String> filmDD;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> monthDD;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JPanel purchasePanel;
    private javax.swing.JLabel purchaseTicket;
    private javax.swing.JButton removeTicket;
    private javax.swing.JLabel selectDate;
    private javax.swing.JLabel selectFilm;
    private javax.swing.JLabel selectTicket;
    private javax.swing.JLabel selectTime;
    private javax.swing.JLabel summary;
    private javax.swing.JButton summaryBtn;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JComboBox<String> ticketDD;
    private javax.swing.JComboBox<String> timeDD;
    private javax.swing.JComboBox<String> yearDD;
    // End of variables declaration//GEN-END:variables
}
